# For developer devint
name: Deploy for devint

on:
  push:
    branches:
      - develop
      - workflow
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.husky/**'
      - '.vscode/**'
      - 'docs/**'
      - 'jest/**'
      - 'mocks/**'
      - 'playwright/**'
      - 'stubs/**'
      - 'tools/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zkmelabs
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: zkmelabs/blockscout-frontend:develop
          cache-to: type=gha
          cache-from: type=gha
          build-args: |
            GIT_COMMIT_SHA=${{ env.SHORT_SHA }}
            GIT_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }}


  deploy-with-docker-compose:
    if: false
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEVINT2_SERVER_HOST }}
          username: ${{ secrets.DEVINT2_SERVER_USERNAME }}
          password: ${{ secrets.DEVINT2_SERVER_PASSWORD }}
          script: |
            sudo docker compose -f /data/blockscout/docker-compose/docker-compose.mechain.devint.yml up --build -d

  deploy-with-k8s:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: clone
        uses: appleboy/ssh-action@v1.0.3
        if: false
        with:
          host: ${{ secrets.DEV0_SERVER_HOST }}
          username: ${{ secrets.DEV0_SERVER_USER }}
          password: ${{ secrets.DEV0_SERVER_PASSWORD }}
          script: |
            mkdir /tmp/deploy && cd /tmp/deploy
            git clone --depth 1 https://git.bitkinetic.com/ops/k8s-hk-rke2.git && cd k8s-hk-rke2
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV0_SERVER_HOST }}
          username: ${{ secrets.DEV0_SERVER_USER }}
          password: ${{ secrets.DEV0_SERVER_PASSWORD }}
          script: |
            cd /tmp/deploy/k8s-hk-rke2/mechain-helm-charts
            echo "${{ secrets.KUBECONFIG_DEV }}" > kubeconfig.yaml
            helm --kubeconfig kubeconfig.yaml -n mechain-dev upgrade blockscout blockscout -f blockscout/values_devint.yaml --wait
      - name: clean
        uses: appleboy/ssh-action@v1.0.3
        if: false
        with:
          host: ${{ secrets.DEV0_SERVER_HOST }}
          username: ${{ secrets.DEV0_SERVER_USER }}
          password: ${{ secrets.DEV0_SERVER_PASSWORD }}
          script: |
            rm -rf /tmp/deploy/