# For developer testing
name: Build and Push Docker Image
on:
  push:
    branches:
      - main
      - cicd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # todo: using docker/build-push-action, Reference: https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: kevin2025/blockscout-frontend:latest

  deploy-with-docker-compose:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEVINT2_SERVER_HOST }}
          username: ${{ secrets.DEVINT2_SERVER_USERNAME }}
          password: ${{ secrets.DEVINT2_SERVER_PASSWORD }}
          script: |
            sudo docker compose -f /data/blockscout/docker-compose/docker-compose.mechain.devint.yml up --build -d