# For developer devint
name: Deploy for devint

on:
  push:
    branches:
      - develop
      - workflow
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.husky/**'
      - '.vscode/**'
      - 'docs/**'
      - 'jest/**'
      - 'mocks/**'
      - 'playwright/**'
      - 'stubs/**'
      - 'tools/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_image:
    name: Publish Docker Image
    uses: './.github/workflows/publish-image.yml'
    secrets: inherit
    with:
     tags: zkmelabs/blockscout-frontend:develop

  deploy_with_k8s:
    runs-on: ubuntu-latest
    needs: publish_image
    steps:
      - name: "Deploy new Deployment"
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_DEV }}
        with:
          args: -n mechain-dev rollout restart deployment blockscout-frontend

      - name: "Check Deployment"
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG_DEV }}
        with:
          args: -n mechain-dev rollout status deployment blockscout-frontend --timeout=600s