# For testnet
name: Deploy for release

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zkmelabs
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Get Github tag
        id: meta
        run: |
          echo "tag=$(git describe --always --tags --match='v*')" >> "$GITHUB_OUTPUT"

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: zkmelabs/blockscout-frontend:latest, zkmelabs/blockscout-frontend:${{ steps.meta.outputs.tag }}
          cache-to: type=gha
          cache-from: type=gha
          build-args: |
            GIT_COMMIT_SHA=${{ env.SHORT_SHA }}
            GIT_TAG=${{ github.ref_type == 'tag' && github.ref_name || '' }}
